SELECT * FROM ALL_OBJECTS WHERE OWNER = 'EINTERFACE' AND OBJECT_NAME LIKE 'TEST_%';


-- // SCRIPT PARA PRUEBAS //
CREATE TABLE EINTERFACE.TEST_CLIENTES (
DNI        CHAR(8)      PRIMARY KEY,
NOMBRE     VARCHAR2(35) NOT NULL,
APELLIDO   VARCHAR2(35) NOT NULL,
EMAIL      VARCHAR2(35) NOT NULL,
TELEFONO   NUMBER
);

--// SELECT * FROM EINTERFACE.TEST_CLIENTES;

-- INSERT
CREATE OR REPLACE PROCEDURE einterface.TEST_SP_INSERT_CLIENTE (
        P_DNI        IN EINTERFACE.TEST_CLIENTES.DNI%TYPE,
        P_NOMBRE     IN EINTERFACE.TEST_CLIENTES.NOMBRE%TYPE,
        P_APELLIDO   IN EINTERFACE.TEST_CLIENTES.APELLIDO%TYPE,
        P_EMAIL      IN EINTERFACE.TEST_CLIENTES.DNI%TYPE,
        P_TELEFONO   IN EINTERFACE.TEST_CLIENTES.DNI%TYPE,
        P_RESULT     OUT VARCHAR2
  ) IS
  BEGIN
    INSERT INTO EINTERFACE.TEST_CLIENTES (
        DNI         ,
        NOMBRE      ,
        APELLIDO    ,
        EMAIL       ,
        TELEFONO  
    ) VALUES (
        P_DNI       ,
        P_NOMBRE    ,
        P_APELLIDO  ,
        P_EMAIL     ,
        P_TELEFONO  
    );
    P_RESULT := 'SE EJECUTO CORRECTAMENTE';
    COMMIT;
  EXCEPTION WHEN OTHERS THEN
    P_RESULT := 'ERROR AL INSERTAR';
    ROLLBACK;
  END;
/
-- UPDATE
CREATE OR REPLACE PROCEDURE einterface.TEST_SP_UPDATE_CLIENTE (
        P_DNI        IN EINTERFACE.TEST_CLIENTES.DNI%TYPE,
        P_NOMBRE     IN EINTERFACE.TEST_CLIENTES.NOMBRE%TYPE,
        P_APELLIDO   IN EINTERFACE.TEST_CLIENTES.APELLIDO%TYPE,
        P_EMAIL      IN EINTERFACE.TEST_CLIENTES.EMAIL%TYPE,
        P_TELEFONO   IN EINTERFACE.TEST_CLIENTES.TELEFONO%TYPE,
        P_RESULT     OUT VARCHAR2
  ) IS
  BEGIN
    UPDATE EINTERFACE.TEST_CLIENTES 
       SET NOMBRE    = P_NOMBRE,
           APELLIDO  = P_APELLIDO,
           EMAIL     = P_EMAIL,
           TELEFONO  = P_TELEFONO
     WHERE DNI = P_DNI;
    P_RESULT := 'SE EJECUTO CORRECTAMENTE';
    COMMIT;
  EXCEPTION WHEN OTHERS THEN
    P_RESULT := 'ERROR AL ACTUALIZAR';
    ROLLBACK;
  END;
/
-- DELETE
CREATE OR REPLACE PROCEDURE einterface.TEST_SP_DELETE_CLIENTE (
        P_DNI        IN EINTERFACE.TEST_CLIENTES.DNI%TYPE,
        P_RESULT     OUT VARCHAR2
  ) IS
  BEGIN
    DELETE FROM EINTERFACE.TEST_CLIENTES
     WHERE DNI = P_DNI;
    P_RESULT := 'SE EJECUTO CORRECTAMENTE';
    COMMIT;
  EXCEPTION WHEN OTHERS THEN
    P_RESULT := 'ERROR AL ELIMINAR';
    ROLLBACK;
  END;
/
-- SELECT
CREATE OR REPLACE PROCEDURE einterface.TEST_SP_SELECT_CLIENTE (
        P_CURSOR     OUT SYS_REFCURSOR
  ) IS
  BEGIN
    OPEN P_CURSOR FOR
       SELECT DNI        ,
              NOMBRE     ,
              APELLIDO   ,
              EMAIL      ,
              TELEFONO   
         FROM EINTERFACE.TEST_CLIENTES;
  END;
/

SELECT * FROM ALL_OBJECTS WHERE OWNER = 'EINTERFACE' AND OBJECT_NAME LIKE 'TEST_%';
/

-- // DROP OBJECTS
/*
DROP TABLE EINTERFACE.TEST_CLIENTES;
DROP PROCEDURE EINTERFACE.TEST_SP_INSERT_CLIENTE;
DROP PROCEDURE EINTERFACE.TEST_SP_UPDATE_CLIENTE;
DROP PROCEDURE EINTERFACE.TEST_SP_DELETE_CLIENTE;
DROP PROCEDURE EINTERFACE.TEST_SP_SELECT_CLIENTE;
*/
